using Godot;
using System;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

public partial class TrainingArenaSmoke : Node
{
    public override async void _Ready()
    {
        try { await Run(); GD.Print("CSHARP_TRAINING_ARENA_SMOKE_OK"); GetTree().Quit(0); }
        catch (Exception e) { GD.PushError("CSHARP_SMOKE_FAILED: " + e); GetTree().Quit(1); }
    }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private async Task Run()
    {
        BattleOutcomeTest.Run();
        
        var arena = GD.Load<PackedScene>("res://scenes/training_arena.tscn").Instantiate<TrainingArena>(); AddChild(arena); await Frame(); await Frame();
        Check(arena.content.heroes.Count == 4, "必须加载4张英雄资源"); Check(arena.content.heroes[1].character_number == 2, "刺客编号必须为2");
        arena.GetNode<CheckButton>("%TestMode").ButtonPressed = true; arena.GetNode<Button>("%OpenTestEditor").EmitSignal(Button.SignalName.Pressed); await Frame(); arena.GetNode<OptionButton>("%Category").Select(2); arena.GetNode<OptionButton>("%Category").EmitSignal(OptionButton.SignalName.ItemSelected, 2); await Frame(); var heroTargets = arena.GetNode<OptionButton>("%Target"); Check(heroTargets.GetItemText(0) == "1 · 铁卫 · 先锋", "先锋必须显示编号、名称和职业"); Check(heroTargets.GetItemText(1) == "2 · 训练用木桩 · 刺客", "刺客必须同时显示编号、名称和职业"); Check(heroTargets.GetItemText(2) == "3 · 风羽 · 斥候", "斥候必须显示编号、名称和职业"); Check(heroTargets.GetItemText(3) == "4 · 律祷 · 祭司", "祭司必须显示编号、名称和职业"); arena.GetNode<AcceptDialog>("%TestEditorDialog").Hide();
        Check(arena.content.cards.Count == 30 && arena.content.cards.Select(c => c.id.ToString()).Distinct().Count() == 30, "规范化后的30张锦囊未完整加载");
        Check(arena.content.cards.Count(c => c.card_kind == CardDefinition.CardKind.Active) == 15 && arena.content.cards.Count(c => c.card_kind == CardDefinition.CardKind.Passive) == 15, "主动/被动锦囊分类错误");
        Check(arena.content.cards.All(c => c.logic_mode == "LUA") && arena.content.cards.Select(c => c.lua_script).Distinct().Count() == 30, "30张卡没有全部使用独立Lua入口");
        CardSemanticValidator.Validate(arena.content.cards);
        using (var resolver = new CardResolver()) { Check(resolver.LuaAvailable, "Lua GDExtension未加载"); Check(resolver.ValidateSandboxIsolation(out var isolationError), "Lua沙盒隔离失败：" + isolationError); }
        var variableDefinition = arena.content.cards.First(c => c.id.ToString() == "card_exhaustive_scheme"); var sampleDefinition = arena.content.cards.First(c => c != variableDefinition);
        Check(variableDefinition.cost_mode == "VARIABLE_AP" && new CardInstance(variableDefinition).CurrentCost(4, 5) == 4, "V2变量费用没有固定取当前全部AP");
        using (var validator = new CardResolver()) foreach (var definition in arena.content.cards) Check(validator.ValidateLua(definition.lua_script, out var validationError), $"{definition.display_name} Lua语法检查失败：{validationError}");
        var ownerDeck = new DeckState(); var originalDeck = new DeckState(); var ownershipBattle = new BattleState(ownerDeck, originalDeck, 11); ownerDeck.Setup([], "player"); originalDeck.Setup([], "ai"); var enemyOriginal = new CardInstance(sampleDefinition, "ai") { Zone = CardInstance.ZoneKind.Hand }; originalDeck.Hand.Add(enemyOriginal); var stealDefinition = arena.content.cards.First(c => c.handler_key == "STEAL_TEMPORARY"); var stealCard = new CardInstance(stealDefinition); var stealContext = new CardExecutionContext { State = ownershipBattle, Card = stealCard, OwnerDeck = ownerDeck, OpponentDeck = originalDeck, Log = _ => { } }; Check(new CardApi(stealContext).StealRandomOpponentCard() && originalDeck.DiscardPile.Contains(enemyOriginal) && ownerDeck.Hand.Single().IsTemporaryCopy && ownerDeck.Hand.Single().CurrentCost() == 0, "V2拿来主义没有弃置敌方原牌并生成0费临时复制");
        var rabbitDefinition = arena.content.cards.First(c => c.handler_key == "SUMMON_DELAYED_RABBIT"); var rabbitCard = new CardInstance(rabbitDefinition); ownershipBattle.CurrentPassiveEvent = new PassiveEventContext { EventKey = "ENEMY_SLOT_EMPTY", SubjectOwnerId = "ai", SubjectSlotIndex = 0 }; new CardApi(new CardExecutionContext { State = ownershipBattle, Card = rabbitCard, OwnerDeck = ownerDeck, OpponentDeck = originalDeck, Log = _ => { } }).SummonDelayedRabbit(); Check(ownershipBattle.PendingSummons.Single().Unit is { Hp: 30, Attack: 0, CanAttack: false, CanRetaliate: false, CardTargetable: false, CountsForOutcome: false, TriggersHeroDeath: false }, "V2兔子正式数值或交互标记错误");
        var passiveDefinition = arena.content.cards.First(c => c.handler_key == "CANCEL_DAMAGE"); var passive = new CardInstance(passiveDefinition); Check(ownershipBattle.SetPassive("player", 2, passive), "BattleState伏牌登记失败"); var triggered = new PassiveTriggerResolver().Collect(ownershipBattle, "player", "BEFORE_DAMAGE"); Check(triggered.Count == 1 && triggered[0].SlotIndex == 2, "被动事件解析或位置记录错误");
        var capacityBattle = new BattleState(new DeckState(), new DeckState(), 12);
        Check(capacityBattle.SetPassive("player", 0, new CardInstance(passiveDefinition)) && capacityBattle.SetPassive("player", 1, new CardInstance(passiveDefinition)) && capacityBattle.SetPassive("player", 2, new CardInstance(passiveDefinition)), "战门应允许同一方放置三张伏牌");
        var nextGate = capacityBattle.NextPassiveGateIndex("player"); var fourthPlaced = capacityBattle.SetPassive("player", 3, new CardInstance(passiveDefinition));
        Check(nextGate == -1 && !fourthPlaced, $"战门没有严格限制每方最多三张伏牌：next={nextGate}, fourth={fourthPlaced}, count={capacityBattle.Passives.Count}");
        var lifecycleDeck = new DeckState(); lifecycleDeck.Setup(arena.content.cards.Take(12), "player"); Check(lifecycleDeck.Draw(4).Count == 4, "自身回合开始必须抽四张牌"); Check(lifecycleDeck.Draw(20).Count == 4 && lifecycleDeck.Hand.Count == DeckState.HandLimit, "全局手牌上限必须为8张"); var retained = lifecycleDeck.Hand.ToList(); Check(lifecycleDeck.DiscardRemainingHand() == 8 && retained.All(lifecycleDeck.DiscardPile.Contains) && lifecycleDeck.Hand.Count == 0, "回合结束时未使用手牌必须全部进入弃牌堆");
        var protectedDeck = new DeckState(); protectedDeck.Setup([], "player"); var protectedCard = new CardInstance(sampleDefinition); var expiringCopy = new CardInstance(sampleDefinition) { IsTemporaryCopy = true, ExileAtTurnEnd = true }; protectedDeck.Hand.Add(protectedCard); protectedDeck.Hand.Add(expiringCopy); Check(protectedDeck.DiscardRemainingHand(true) == 0 && protectedDeck.Hand.Single() == protectedCard && protectedDeck.ExilePile.Single() == expiringCopy, "神器2应保留普通手牌，但临时复制仍须在回合结束放逐"); protectedDeck.FinishPlayedCard(protectedCard); var playedCopy = new CardInstance(sampleDefinition) { IsTemporaryCopy = true, ExileAtTurnEnd = true }; protectedDeck.Hand.Add(playedCopy); protectedDeck.FinishPlayedCard(playedCopy); Check(protectedDeck.ExilePile.Contains(playedCopy) && !protectedDeck.DiscardPile.Contains(playedCopy), "临时复制使用后必须立即放逐");
        var guideDefinition = arena.content.cards.First(c => c.handler_key == "DISCARD_DRAW_AP"); var guideDeck = new DeckState(); var guideEnemy = new DeckState(); var guideBattle = new BattleState(guideDeck, guideEnemy, 13) { PlayerActionPoints = 1 }; guideDeck.Setup([], "player"); guideEnemy.Setup([], "ai"); var guide = new CardInstance(guideDefinition); guideDeck.Hand.Add(guide); guideDeck.Hand.Add(new CardInstance(sampleDefinition)); guideDeck.Hand.Add(new CardInstance(sampleDefinition)); guideDeck.DrawPile.Add(new CardInstance(sampleDefinition)); guideDeck.DrawPile.Add(new CardInstance(sampleDefinition)); new CardApi(new CardExecutionContext { State = guideBattle, Card = guide, OwnerDeck = guideDeck, OpponentDeck = guideEnemy, Log = _ => { } }).ResolveCardEffect("DISCARD_DRAW_AP"); Check(guideDeck.DiscardPile.Count == 2 && guideDeck.Hand.Count == 3 && guideBattle.PlayerActionPoints == 3, "迷蒙指引在不足3张其他手牌时必须全部弃置并继续结算");
        var exhaustive = arena.content.cards.First(c => c.handler_key == "CONSUME_AP_REFUND_NEXT"); var apBattle = new BattleState(new DeckState(), new DeckState(), 14) { PlayerActionPoints = 3 }; new CardApi(new CardExecutionContext { State = apBattle, Card = new CardInstance(exhaustive), OwnerDeck = apBattle.PlayerDeck, OpponentDeck = apBattle.EnemyDeck, Log = _ => { } }).ResolveCardEffect("CONSUME_AP_REFUND_NEXT"); Check(apBattle.PlayerActionPoints == 0 && apBattle.PlayerNextTurnActionPointsOverride == 4, "机关算尽必须把下回合初始AP设置为当前剩余AP+1");
        var dummy = arena.GetNode<CheckButton>("%DummyMode"); dummy.ButtonPressed = true; arena.ResetTraining(); await Frame();
        arena.GetNode<Button>("%HeroBag").EmitSignal(Button.SignalName.Pressed); await Frame(); var heroButton = arena.GetNode<VBoxContainer>("%HeroList").GetChildren().OfType<Button>().First(); heroButton.EmitSignal(Button.SignalName.Pressed);
        var ally = arena.GetNode<HBoxContainer>("%AllyRow").GetChild<UnitSlot>(0); var ally2 = arena.GetNode<HBoxContainer>("%AllyRow").GetChild<UnitSlot>(1); var enemy = arena.GetNode<HBoxContainer>("%EnemyRow").GetChild<UnitSlot>(0); ally.Activate(); await Delay(.5); Check(ally.Unit?.Alive == true, "英雄部署失败"); Check((int)GetPrivate(arena, "_ap")! == BattleState.DefaultActionPoints, "英雄部署不应消耗行动点"); arena.GetNode<Button>("%HeroBag").EmitSignal(Button.SignalName.Pressed); await Frame(); var secondHeroButton = arena.GetNode<VBoxContainer>("%HeroList").GetChildren().OfType<Button>().First(); secondHeroButton.EmitSignal(Button.SignalName.Pressed); ally2.Activate(); await Frame(); Check(ally2.Unit == null, "每回合只能部署一名英雄");
        ally.Activate(); enemy.Activate(); await Frame(); var hp = enemy.Unit!.Hp; Check(enemy.DisplayText.Contains("预计"), "第一次点目标未写入攻击预览"); enemy.Activate(); await Delay(1.5); Check(enemy.Unit.Hp < hp, "第二次点目标未结算攻击"); var hpAfterFirstAttack = enemy.Unit.Hp; ally.Activate(); enemy.Activate(); enemy.Activate(); await Frame(); Check(enemy.Unit.Hp == hpAfterFirstAttack, "同一英雄每回合只能攻击一次");
        var deck = (DeckState)GetPrivate(arena, "_deck")!; var stealDef = arena.content.cards.First(c => c.handler_key == "STEAL_TEMPORARY"); var counterDef = arena.content.cards.First(c => c.handler_key == "CANCEL_DRAW");
        var playerCounter = new CardInstance(counterDef); deck.Hand.Add(playerCounter); arena.RefreshAll(); await Frame(); var passiveTile = arena.GetNode<HandFan>("%Hand").GetChildren().OfType<CardTile>().First(t => t.Card == playerCounter); passiveTile.EmitSignal(Button.SignalName.Pressed); await Frame(); var gate = arena.GetNode<PassiveGate>("%PassiveGate"); Check(gate.PlayerCardCount == 1 && gate.EnemyCardCount == 0 && !deck.Hand.Contains(playerCounter), "被动锦囊必须从手牌背面设置到独立战门");
        var liveBattle = (BattleState)GetPrivate(arena, "_battle")!; var enemyCounter = new CardInstance(counterDef, "ai"); Check(liveBattle.SetPassive("ai", liveBattle.NextPassiveGateIndex("ai"), enemyCounter), "测试敌方伏牌登记失败"); arena.RefreshAll(); await Frame(); Check(gate.CardCount == 2 && gate.PlayerCardCount == 1 && gate.EnemyCardCount == 1, "战门没有同时统计敌我双方伏牌"); gate.EmitSignal(Control.SignalName.GuiInput, new InputEventMouseButton { ButtonIndex = MouseButton.Left, Pressed = true }); await Frame(); Check(gate.Expanded, "单击战门没有横向展开敌我双方伏牌"); var ownFace = gate.ExpandedPlayerCard; Check(ownFace != null && ownFace.Text.Contains(playerCounter.Definition.display_name), "展开战门没有显示我方伏牌卡面，或错误显示了敌方卡面"); ownFace!.EmitSignal(Control.SignalName.GuiInput, new InputEventMouseButton { ButtonIndex = MouseButton.Right, Pressed = true }); await Frame(); Check(arena.GetNode<BattleRightSidebar>("%ContentHost").Mode == BattleRightSidebar.RightPanelMode.CardDetail, "右键我方伏牌没有打开右侧卡牌简介");
        SetPrivate(arena, "_ap", 3); var steal = new CardInstance(stealDef); deck.Hand.Add(steal); arena.RefreshAll(); await Frame(); var tile = arena.GetNode<HandFan>("%Hand").GetChildren().OfType<CardTile>().First(t => t.Card == steal); tile.EmitSignal(Button.SignalName.Pressed); await Frame(); tile.EmitSignal(Button.SignalName.Pressed); await Delay(2.0); Check(deck.DiscardPile.Contains(steal), "拿来主义未进入弃牌堆");
        arena.QueueFree(); await Frame();
    }
    private static object? GetPrivate(object target, string name) => target.GetType().GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(target);
    private static void SetPrivate(object target, string name, object value) => target.GetType().GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)!.SetValue(target, value);
    private async Task Frame() => await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame);
    private async Task Delay(double seconds) => await ToSignal(GetTree().CreateTimer(seconds), SceneTreeTimer.SignalName.Timeout);
}
