using Godot;
using System;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

public partial class TrainingArenaSmoke : Node
{
    public override async void _Ready()
    {
        try { await Run(); GD.Print("CSHARP_TRAINING_ARENA_SMOKE_OK"); GetTree().Quit(0); }
        catch (Exception e) { GD.PushError("CSHARP_SMOKE_FAILED: " + e); GetTree().Quit(1); }
    }
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private async Task Run()
    {
        var arena = GD.Load<PackedScene>("res://scenes/training_arena.tscn").Instantiate<TrainingArena>(); AddChild(arena); await Frame(); await Frame();
        Check(arena.content.heroes.Count == 4, "必须加载4张英雄资源"); Check(arena.content.heroes[1].character_number == 2, "刺客编号必须为2");
        arena.GetNode<CheckButton>("%TestMode").ButtonPressed = true; arena.GetNode<Button>("%OpenTestEditor").EmitSignal(Button.SignalName.Pressed); await Frame(); arena.GetNode<OptionButton>("%Category").Select(2); arena.GetNode<OptionButton>("%Category").EmitSignal(OptionButton.SignalName.ItemSelected, 2); await Frame(); var heroTargets = arena.GetNode<OptionButton>("%Target"); Check(heroTargets.GetItemText(0) == "1 · 铁卫 · 先锋", "先锋必须显示编号、名称和职业"); Check(heroTargets.GetItemText(1) == "2 · 训练用木桩 · 刺客", "刺客必须同时显示编号、名称和职业"); Check(heroTargets.GetItemText(2) == "3 · 风羽 · 斥候", "斥候必须显示编号、名称和职业"); Check(heroTargets.GetItemText(3) == "4 · 律祷 · 祭司", "祭司必须显示编号、名称和职业"); arena.GetNode<AcceptDialog>("%TestEditorDialog").Hide();
        Check(arena.content.cards.Count == 30 && arena.content.cards.Select(c => c.id.ToString()).Distinct().Count() == 30, "规范化后的30张锦囊未完整加载");
        Check(arena.content.cards.Count(c => c.card_kind == CardDefinition.CardKind.Active) == 15 && arena.content.cards.Count(c => c.card_kind == CardDefinition.CardKind.Passive) == 15, "主动/被动锦囊分类错误");
        Check(arena.content.cards.All(c => c.logic_mode == "LUA") && arena.content.cards.Select(c => c.lua_script).Distinct().Count() == 30, "30张卡没有全部使用独立Lua入口");
        CardSemanticValidator.Validate(arena.content.cards);
        using (var resolver = new CardResolver()) { Check(resolver.LuaAvailable, "Lua GDExtension未加载"); Check(resolver.ValidateSandboxIsolation(out var isolationError), "Lua沙盒隔离失败：" + isolationError); }
        var luaDefinition = arena.content.cards.First(c => c.id.ToString() == "card_exhaustive_scheme"); var builtinDefinition = arena.content.cards.First(c => c != luaDefinition);
        Check(luaDefinition.logic_mode == "LUA" && luaDefinition.lua_script.EndsWith("exhaustive_scheme.lua", StringComparison.Ordinal), "Lua卡牌元数据未加载");
        var luaDeck = new DeckState(); var luaOpponent = new DeckState(); var luaCard = new CardInstance(luaDefinition); var otherCard = new CardInstance(builtinDefinition); luaDeck.Hand.Add(luaCard); luaDeck.Hand.Add(otherCard);
        var luaBattle = new BattleState(luaDeck, luaOpponent, 7); using (var resolver = new CardResolver()) { Check(resolver.LuaAvailable, "Lua GDExtension未加载"); var context = new CardExecutionContext { State = luaBattle, Card = luaCard, OwnerDeck = luaDeck, OpponentDeck = luaOpponent, Log = _ => { } }; Check(resolver.Resolve(context, out var luaError), "Lua卡牌执行失败：" + luaError); Check(otherCard.CurrentCost() == 0, "Lua Card API未修改手牌费用"); }
        using (var validator = new CardResolver()) foreach (var definition in arena.content.cards) { Check(validator.ValidateLua(definition.lua_script, out var validationError), $"{definition.display_name} Lua语法检查失败：{validationError}"); var owner = new DeckState(); owner.Setup([], "player"); var opponent = new DeckState(); opponent.Setup([], "ai"); opponent.Hand.Add(new(builtinDefinition, "ai")); opponent.Hand.Add(new(builtinDefinition, "ai")); var state = new BattleState(owner, opponent, 101); var source = new UnitState { Definition = arena.content.heroes[0], Name = "脚本源", Type = "先锋", Hp = 30, MaxHp = 30, Attack = 4 }; var target = new UnitState { Definition = arena.content.heroes[1], Name = "脚本目标", Type = "刺客", Hp = 30, MaxHp = 30, Attack = 4 }; state.SynchronizeUnits([source], [target]); var instance = new CardInstance(definition); owner.Hand.Add(instance); var context = new CardExecutionContext { State = state, Card = instance, OwnerDeck = owner, OpponentDeck = opponent, Source = source, Target = target, Log = _ => { } }; Check(validator.Resolve(context, out var executionError), $"{definition.display_name} Lua试运行失败：{executionError}"); }
        var eventTarget = new UnitState { Definition = arena.content.heroes[0], Name = "事件测试", Hp = 20, MaxHp = 20, Attack = 1 }; var damageCard = new CardInstance(arena.content.cards.First(c => c.handler_key == "DAMAGE_STAR_ALL")); var eventBattle = new BattleState(new(), new(), 9); var beforeDamageSeen = false; eventBattle.Events.Subscribe(BattleEvent.BeforeDamage, data => { beforeDamageSeen = true; data.Amount = 3; }); var damageContext = new CardExecutionContext { State = eventBattle, Card = damageCard, OwnerDeck = eventBattle.PlayerDeck, OpponentDeck = eventBattle.EnemyDeck, Target = eventTarget, Log = _ => { } }; using (var resolver = new CardResolver()) Check(resolver.Resolve(damageContext, out var builtinError), "内置Handler执行失败：" + builtinError); Check(beforeDamageSeen && eventTarget.Hp == 17, "内置Handler没有经过BattleEvent/Card API结算");
        var ownerDeck = new DeckState(); ownerDeck.Setup([], "player"); var originalDeck = new DeckState(); originalDeck.Setup([], "ai"); var borrowed = new CardInstance(builtinDefinition, "ai") { Zone = CardInstance.ZoneKind.Hand }; originalDeck.Hand.Add(borrowed); var stealDefinition = arena.content.cards.First(c => c.handler_key == "STEAL_TEMPORARY"); var stealCard = new CardInstance(stealDefinition); var ownershipBattle = new BattleState(ownerDeck, originalDeck, 11); var stealContext = new CardExecutionContext { State = ownershipBattle, Card = stealCard, OwnerDeck = ownerDeck, OpponentDeck = originalDeck, Log = _ => { } }; Check(new CardApi(stealContext).StealRandomOpponentCard() && ownerDeck.Hand.Contains(borrowed) && borrowed.CurrentCost() == 0, "临时偷牌没有进入当前拥有者手牌或费用未归零"); ownershipBattle.AdvanceTurn(); Check(!ownerDeck.Hand.Contains(borrowed) && originalDeck.DiscardPile.Contains(borrowed) && borrowed.OwnerId == "ai", "临时偷牌未在回合结束回到原拥有者弃牌堆");
        var passiveDefinition = arena.content.cards.First(c => c.handler_key == "CANCEL_DAMAGE"); var passive = new CardInstance(passiveDefinition); Check(ownershipBattle.SetPassive("player", 2, passive), "BattleState伏牌登记失败"); var triggered = new PassiveTriggerResolver().Collect(ownershipBattle, "player", "BEFORE_DAMAGE"); Check(triggered.Count == 1 && triggered[0].SlotIndex == 2, "被动事件解析或位置记录错误");
        var temporaryTarget = new UnitState { Definition = arena.content.heroes[1], Name = "临时转职目标", Type = "无职业", Hp = 10, MaxHp = 10, Attack = 2 }; ownershipBattle.SynchronizeUnits([], [temporaryTarget]); var reincarnation = new CardInstance(arena.content.cards.First(c => c.handler_key == "TEMP_RANDOM_CLASS")); var passiveLuaContext = new CardExecutionContext { State = ownershipBattle, Card = reincarnation, OwnerDeck = ownerDeck, OpponentDeck = originalDeck, Log = _ => { } }; using (var resolver = new CardResolver()) Check(resolver.Resolve(passiveLuaContext, out var passiveLuaError), "被动Lua执行失败：" + passiveLuaError); Check(temporaryTarget.Type != "无职业", "被动Lua没有修改敌方职业"); ownershipBattle.AdvanceTurn(); Check(temporaryTarget.Type == "无职业", "BattleState延迟事件没有恢复临时职业");
        var manipulate = new CardInstance(arena.content.cards.First(c => c.handler_key == "PREPAY_AND_DISCARD")); originalDeck.Hand.Clear(); originalDeck.Hand.Add(new(builtinDefinition, "ai")); originalDeck.Hand.Add(new(builtinDefinition, "ai")); originalDeck.Hand.Add(new(builtinDefinition, "ai")); ownershipBattle.PlayerActionPoints = 3; var manipulateContext = new CardExecutionContext { State = ownershipBattle, Card = manipulate, OwnerDeck = ownerDeck, OpponentDeck = originalDeck, Log = _ => { } }; using (var resolver = new CardResolver()) Check(resolver.Resolve(manipulateContext, out var manipulateError), "操纵世界Lua执行失败：" + manipulateError); Check(ownershipBattle.PlayerActionPoints == 0 && ownershipBattle.PlayerNextTurnBonus == 3 && originalDeck.Hand.Count == 1, "操纵世界没有按Y点行动力预付、弃Y-1张牌并登记返还");
        var dummy = arena.GetNode<CheckButton>("%DummyMode"); dummy.ButtonPressed = true; arena.ResetTraining(); await Frame();
        arena.GetNode<Button>("%HeroBag").EmitSignal(Button.SignalName.Pressed); await Frame(); var heroButton = arena.GetNode<VBoxContainer>("%HeroList").GetChildren().OfType<Button>().First(); heroButton.EmitSignal(Button.SignalName.Pressed);
        var ally = arena.GetNode<HBoxContainer>("%AllyRow").GetChild<UnitSlot>(0); var enemy = arena.GetNode<HBoxContainer>("%EnemyRow").GetChild<UnitSlot>(0); ally.EmitSignal(Button.SignalName.Pressed); await Delay(.5); Check(ally.Unit?.Alive == true, "英雄部署失败");
        ally.EmitSignal(Button.SignalName.Pressed); enemy.EmitSignal(Button.SignalName.Pressed); await Frame(); var hp = enemy.Unit!.Hp; Check(enemy.Text.Contains("预计"), "第一次点目标未写入攻击预览"); enemy.EmitSignal(Button.SignalName.Pressed); await Delay(1.5); Check(enemy.Unit.Hp < hp, "第二次点目标未结算攻击");
        var deck = (DeckState)GetPrivate(arena, "_deck")!; var stealDef = arena.content.cards.First(c => c.handler_key == "STEAL_TEMPORARY"); var counterDef = arena.content.cards.First(c => c.handler_key == "CANCEL_DRAW");
        var playerCounter = new CardInstance(counterDef); deck.Hand.Add(playerCounter); arena.RefreshAll(); await Frame(); var passiveTile = arena.GetNode<HandFan>("%Hand").GetChildren().OfType<CardTile>().First(t => t.Card == playerCounter); passiveTile.EmitSignal(Button.SignalName.Pressed); await Frame(); ally.EmitSignal(Button.SignalName.Pressed); await Frame(); Check(ally.PassiveCard == playerCounter && !deck.Hand.Contains(playerCounter), "被动锦囊必须从手牌背面盖放到英雄槽");
        SetPrivate(arena, "_ap", 3); var steal = new CardInstance(stealDef); deck.Hand.Add(steal); arena.RefreshAll(); await Frame(); var tile = arena.GetNode<HandFan>("%Hand").GetChildren().OfType<CardTile>().First(t => t.Card == steal); tile.EmitSignal(Button.SignalName.Pressed); await Frame(); tile.EmitSignal(Button.SignalName.Pressed); await Delay(2.0); Check(deck.DiscardPile.Contains(steal), "拿来主义未进入弃牌堆");
        arena.QueueFree(); await Frame();
    }
    private static object? GetPrivate(object target, string name) => target.GetType().GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)?.GetValue(target);
    private static void SetPrivate(object target, string name, object value) => target.GetType().GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)!.SetValue(target, value);
    private async Task Frame() => await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame);
    private async Task Delay(double seconds) => await ToSignal(GetTree().CreateTimer(seconds), SceneTreeTimer.SignalName.Timeout);
}
